
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #mvc:
  #  view:
  #    prefix: /WEB-INF/jsp/
  #    suffix: .jsp

server:
  port: 8084